language: java
jdk:
- oraclejdk8
services:
  - docker
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
  - echo "deb https://repos.mesosphere.io/ubuntu/ trusty main" | sudo tee /etc/apt/sources.list.d/mesosphere.list
  - sudo apt-get update -qq
  - sudo apt-get install mesos -y </dev/null
  - eval "$(pyenv init -)"
  - pyenv install --skip-existing 3.6.2
  - pyenv global 3.6.2
branches:
  only:
    - master
sudo: required
dist: trusty
cache:
    directories:
        - $HOME/.m2
        - $HOME/.pyenv
env:
  global:
    - MESOS_NATIVE_JAVA_LIBRARY=/usr/lib/libmesos.so
    - CLJ_HTTP_ASYNC_POOL_TEST_DURATION_MULTIPLIER=5
    - PYENV_ROOT=$HOME/.pyenv
  matrix:
    - COOK_EXECUTOR='1' TEST_DIR=executor DEPS_CMD='travis/setup.sh' TEST_CMD='travis/run_tests.sh'
    - COOK_EXECUTOR='1' TEST_DIR=scheduler DEPS_CMD='travis/setup.sh' TEST_CMD='lein test :all-but-benchmark'
    - COOK_EXECUTOR='1' TEST_DIR=scheduler DEPS_CMD='lein with-profiles +test deps' TEST_CMD='lein test :benchmark'
    - COOK_EXECUTOR='1' TEST_DIR=jobclient DEPS_CMD='mvn dependency:resolve' TEST_CMD='mvn test'
    - COOK_EXECUTOR='1' TEST_DIR=simulator DEPS_CMD='travis/prepare_simulation.sh' TEST_CMD='travis/run_simulation.sh'
    - COOK_EXECUTOR='1' TEST_DIR=integration DEPS_CMD='travis/prepare_integration.sh' TEST_CMD='travis/run_integration.sh'
    - COOK_EXECUTOR='0' TEST_DIR=integration DEPS_CMD='travis/prepare_integration.sh' TEST_CMD='travis/run_integration.sh'
    - COOK_EXECUTOR='1' TEST_DIR=integration DEPS_CMD='travis/prepare_integration.sh' TEST_CMD='travis/run_integration.sh explicit'
matrix:
    fast_finish: true
    allow_failures:
      - env: COOK_EXECUTOR='1' TEST_DIR=scheduler DEPS_CMD='lein with-profiles +test deps' TEST_CMD='lein test :benchmark'
      - env: COOK_EXECUTOR='1' TEST_DIR=integration DEPS_CMD='travis/prepare_integration.sh' TEST_CMD='travis/run_integration.sh explicit'
before_script: (cd $TEST_DIR && $DEPS_CMD)
script: cd $TEST_DIR && $TEST_CMD
