dist: trusty
language: java
jdk: oraclejdk8

branches:
  only:
    - master
    - /^build\/.*$/
    - kubernetes_integration

cache:
  directories:
    - $HOME/.apt-cache
    - $HOME/.local
    - $HOME/.m2

env:
  global:
    - MESOS_NATIVE_JAVA_LIBRARY=/usr/lib/libmesos.so
    - CLJ_HTTP_ASYNC_POOL_TEST_DURATION_MULTIPLIER=5

before_install:
  - pyenv global 3.6
  - echo "Sudo-enabled build? ${TRAVIS_SUDO}"

matrix:
  allow_failures:
    - name: 'Cook Scheduler benchmark tests'

  fast_finish: true

  include:
    - name: 'Cook Scheduler and JobClient unit tests'
      before_script: cd scheduler && ./travis/setup.sh
      script:
        - pushd ../jobclient && mvn test
        - popd && lein with-profile +test test :all-but-benchmark

    - name: 'Cook Scheduler integration tests with Cook Executor and Docker'
      services: docker
      install: sudo ./travis/install_mesos.sh
      before_script: cd integration && ./travis/prepare_integration.sh
      script: ./travis/run_integration.sh --executor=cook --image=python:3.5

    # We want a small rate limit to make the job launch rate limit integration test be stable and not
    # need to launch a lot of jobs. Those low launch rate limit settings would cause other integration
    # tests to break, so we run this test separately.
    - name: 'Cook Scheduler integration tests with job launch rate limit'
      services: docker
      install: sudo ./travis/install_mesos.sh
      before_script: cd integration && ./travis/prepare_integration.sh
      script: ./travis/run_integration_ratelimit.sh

    - name: 'Cook Scheduler Simulator tests'
      services: docker
      install: sudo ./travis/install_mesos.sh
      before_script: cd simulator && ./travis/prepare_simulation.sh
      script: ./travis/run_simulation.sh

    - name: 'Cook Executor tests'
      before_script: cd executor && ./travis/setup.sh
      script: ./travis/run_tests.sh
